# Generated by Django 3.2.13 on 2022-05-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question_text', models.CharField(default='', max_length=200)),
                ('question_type', models.CharField(default='', max_length=100)),
                ('question_level', models.CharField(default='', max_length=100)),
                ('question_category', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('creator_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_2', to='users.user')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_1', to='exams.exam')),
            ],
        ),
    ]
