# Generated by Django 3.2.13 on 2022-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device', models.CharField(default='', max_length=100)),
                ('recording_start_time', models.TimeField(auto_now_add=True)),
                ('recording_end_time', models.TimeField(auto_now_add=True)),
                ('filename', models.CharField(default='', max_length=200)),
                ('final_submission', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
