# Generated by Django 3.2.13 on 2022-05-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('d_o_b', models.DateField(default='')),
                ('nationality', models.CharField(default='', max_length=100)),
                ('native_language', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Not Chosen'), (1, 'Male'), (2, 'Female'), (3, 'Others')], default=0)),
                ('kor_lang_proficiency', models.CharField(default='', max_length=100)),
                ('study_period', models.IntegerField(default='')),
                ('stay_period_kor', models.IntegerField(default='')),
                ('study_purpose', models.CharField(default='', max_length=100)),
                ('study_method', models.CharField(default='', max_length=100)),
                ('self_assessment_level', models.CharField(default='', max_length=100)),
                ('topik_level', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default='')),
                ('organization', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='users.user')),
            ],
        ),
    ]
